name: Build RTL8189FS Driver

on:
  workflow_dispatch:
    inputs:
      kernel_repo:
        description: "Repo source kernel (contoh: https://github.com/user/linux)"
        required: true
      kernel_branch:
        description: "Branch kernel (contoh: main, v6.12, dsb)"
        required: true
      driver_repo:
        description: "Repo driver RTL8189FS"
        required: true
      driver_branch:
        description: "Branch driver (default: master)"
        required: true
        default: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build rtl8189fs module

    steps:
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential bc kmod libelf-dev \
             libssl-dev libncurses-dev flex bison dwarves

    - name: Clone kernel source
      run: |
        git clone --depth=1 --branch "${{ github.event.inputs.kernel_branch }}" \
          "${{ github.event.inputs.kernel_repo }}" kernel-source
        cd kernel-source
        make defconfig
        make modules_prepare

    - name: Clone rtl8189fs driver
      run: |
        git clone --depth=1 --branch "${{ github.event.inputs.driver_branch }}" \
          "${{ github.event.inputs.driver_repo }}" driver-src

    - name: Build module
      run: |
        cd driver-src
        make KSRC=$(pwd)/../kernel-source

    - name: Upload .ko file
      uses: actions/upload-artifact@v4
      with:
        name: rtl8189fs-ko
        path: driver-src/*.ko
