name: Upload Kernel to Release

on:
  workflow_dispatch:
    inputs:
      kernel_url:
        description: 'URL kernel (GitHub / Mediafire / Mega)'
        required: true
        type: string
      kernel_mu:
        description: "Select the kernel source"
        required: false
        default: "s905x4"
        type: choice
        options:
          - s905x4
          - stable
          - dev
          - beta    
          - dtb  

jobs:
  upload_kernel_release:
    runs-on: ubuntu-latest

    steps:
      - name: Extract version from kernel URL
        id: version
        run: |
          url="${{ github.event.inputs.kernel_url }}"
          if [[ "$url" =~ ([0-9]+\.[0-9]+(\.[0-9]+)?) ]]; then
            echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "version=unknown" >> $GITHUB_OUTPUT
          fi

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y aria2 unzip megatools curl

      - name: Download kernel archive (with correct filename)
        run: |
          url="${{ github.event.inputs.kernel_url }}"
          echo "Downloading: $url"

          if [[ "$url" =~ mega\.nz ]]; then
            megadl --path=./downloaded "$url"
            FILE=$(ls downloaded | head -n 1)
            mv "downloaded/$FILE" "$FILE"
          else
            FILE=$(basename "$url")
            curl -L -o "$FILE" "$url"
          fi

          echo "filename=$FILE" >> $GITHUB_ENV

      - name: Extract and repackage
        run: |
          mkdir -p kernel-extracted

          if [[ "$filename" =~ \.zip$ ]]; then
            unzip "$filename" -d kernel-extracted
          elif [[ "$filename" =~ \.tar\.gz$|\.tgz$ ]]; then
            tar -xzf "$filename" -C kernel-extracted
          elif [[ "$filename" =~ \.tar$ ]]; then
            tar -xf "$filename" -C kernel-extracted
          else
            echo "❌ Unsupported archive format: $filename"
            exit 1
          fi

          cd kernel-extracted
          tar -czf ../kernel-${{ steps.version.outputs.version }}.tar.gz *

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: kernel_${{ inputs.kernel_mu }}
          name: Kernel ${{ steps.version.outputs.version }}
          body: |
            ✅ Auto-uploaded kernel: **${{ steps.version.outputs.version }}**
            📦 Source: ${{ github.event.inputs.kernel_url }}
            🧩 Type: `${{ inputs.kernel_mu }}`
          files: kernel-${{ steps.version.outputs.version }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
